name: ubuntu_wizard
description: Shared library for Ubuntu wizards.
publish_to: 'none'

environment:
  sdk: ">=2.15.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  args: ^2.2.0
  collection: ^1.15.0
  crypt: ^4.0.1
  dbus: ^0.6.0
  diacritic: ^0.1.3
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  form_field_validator: ^1.1.0
  get_it: ^7.2.0
  gsettings: ^0.2.0
  intl: ^0.17.0
  password_strength: ^0.2.0
  provider: ^6.0.0
  safe_change_notifier: ^0.1.0
  subiquity_client:
    path: ../subiquity_client
  ubuntu_localizations:
    git:
      url: https://github.com/canonical/ubuntu-flutter-plugins.git
      path: packages/ubuntu_localizations
  ubuntu_logger:
    git:
      url: https://github.com/canonical/ubuntu-flutter-plugins.git
      path: packages/ubuntu_logger
  wizard_router: ^0.7.0
  yaru: ^0.2.0
  yaru_icons: ^0.1.2

dev_dependencies:
  build_runner: ^2.0.5
  effective_dart: ^1.3.2
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
  mockito: 5.0.14
  ubuntu_test:
    path: ../ubuntu_test

flutter:
  plugin:
    platforms:
      linux:
        pluginClass: UbuntuWizardPlugin
