name: ubuntu_wizard
description: Shared library for Ubuntu wizards.
publish_to: 'none'

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=3.0.0"

dependencies:
  args: ^2.2.0
  collection: ^1.15.0
  crypt: ^4.0.1
  diacritic: ^0.1.3
  file: ^6.1.2
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  form_field_validator: ^1.1.0
  intl: ^0.17.0
  password_strength: ^0.2.0
  path: ^1.8.0
  safe_change_notifier: ^0.2.0
  subiquity_client:
    git:
      url: https://github.com/canonical/subiquity_client.dart.git
  ubuntu_localizations: ^0.0.5
  ubuntu_logger: ^0.0.1
  ubuntu_service: ^0.2.0
  ubuntu_widgets:
    git:
      url: https://github.com/canonical/ubuntu-flutter-plugins.git
      path: packages/ubuntu_widgets
  url_launcher: ^6.1.0
  wizard_router: ^0.9.4
  yaru: ^0.5.0
  yaru_widgets: ^2.1.0

dev_dependencies:
  build_runner: ^2.2.0
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  mockito: 5.3.2
  plugin_platform_interface: ^2.1.2
  ubuntu_test:
    path: ../ubuntu_test
  url_launcher_platform_interface: ^2.0.5
