name: glibc
description: "glibc FFI bindings"
publish_to: "none"

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  collection: ^1.16.0
  ffi: ^1.1.2

dev_dependencies:
  ffigen: ^4.1.2
  flutter_lints: ^2.0.0
