name: ubuntu_desktop_installer
description: Ubuntu Desktop Installer
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.17.0 <3.0.0'
  flutter: '>=3.0.0'

dependencies:
  async: ^2.8.2
  collection: ^1.15.0
  dartx: ^1.0.0
  dbus: ^0.7.3
  diacritic: ^0.1.3
  file: ^6.1.0
  filesize: ^2.0.0
  flutter:
    sdk: flutter
  flutter_html: 3.0.0-alpha.6
  flutter_localizations:
    sdk: flutter
  flutter_markdown: ^0.6.2
  flutter_spinbox: ^0.13.0
  flutter_svg: ^1.1.0
  form_field_validator: ^1.1.0
  gsettings: ^0.2.5
  handy_window: ^0.3.0
  intl: ^0.17.0
  meta: ^1.7.0
  nm: ^0.5.0
  path: ^1.8.0
  provider: ^6.0.0
  safe_change_notifier: ^0.2.0
  scroll_to_index: ^3.0.0
  split_view: ^3.2.1
  stdlibc: ^0.1.0
  subiquity_client:
    git:
      url: https://github.com/canonical/subiquity_client.dart.git
  timezone_map:
    git:
      url: https://github.com/canonical/ubuntu-flutter-plugins.git
      path: packages/timezone_map
  ubuntu_localizations: ^0.0.5
  ubuntu_logger: ^0.0.1
  ubuntu_service: ^0.2.0
  ubuntu_widgets:
    git:
      url: https://github.com/canonical/ubuntu-flutter-plugins.git
      path: packages/ubuntu_widgets
  ubuntu_wizard:
    git:
      url: https://github.com/canonical/ubuntu-desktop-installer.git
      path: packages/ubuntu_wizard
  udev: ^0.0.2
  upower: ^0.7.0
  yaru: ^0.5.0
  yaru_icons: ^1.0.0
  yaru_widgets: ^2.1.1

dev_dependencies:
  build_runner: ^2.2.0
  fake_async: ^1.2.0
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  mockito: 5.3.2
  ubuntu_test:
    path: ../ubuntu_test
  yaml: ^3.1.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/choose_your_look/
    - assets/install_alongside/
    - assets/installation_complete/
    - assets/installation_slides/
    - assets/installation_slides/icons/
    - assets/installation_slides/screenshots/
    - assets/select_guided_storage/
    - assets/try_or_install/
    - assets/turn_off_bitlocker/
    - assets/turn_off_rst/
    - assets/welcome/
