name: ubuntu_desktop_installer
description: Ubuntu Desktop Installer
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '^3.0.6'
  flutter: '^3.10.6'

dependencies:
  collection: ^1.15.0
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.3.6
  flutter_spinbox: ^0.13.0
  handy_window: ^0.3.0
  subiquity_client:
    path: ../../vendor/ubuntu-desktop-provision/packages/subiquity_client
  ubuntu_bootstrap:
    path: ../../vendor/ubuntu-desktop-provision/packages/ubuntu_bootstrap
  ubuntu_provision:
    path: ../../vendor/ubuntu-desktop-provision/packages/ubuntu_provision
  ubuntu_provision_test:
    path: ../../vendor/ubuntu-desktop-provision/packages/ubuntu_provision_test
  ubuntu_utils:
    path: ../../vendor/ubuntu-desktop-provision/packages/ubuntu_utils
  ubuntu_wizard:
    path: ../../vendor/ubuntu-desktop-provision/packages/ubuntu_wizard
  yaru: ^0.9.0
  yaru_icons: ^1.0.0
  yaru_widgets: ^2.5.0

dev_dependencies:
  build_runner: ^2.2.0
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  mockito: 5.4.2
  subiquity_test:
    path: ../../vendor/ubuntu-desktop-provision/packages/subiquity_client/packages/subiquity_test
  ubuntu_test: ^0.1.0-0
  yaml: ^3.1.0
  yaru_test: ^0.1.0

flutter:
  uses-material-design: true
  assets:
    - assets/
