name: ubuntu_test
description: Shared test extensions and mocks.
publish_to: 'none'

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=3.0.0"

dependencies:
  build_runner: ^2.2.0
  flutter:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  gsettings: ^0.2.5
  mockito: 5.3.2
  path: ^1.8.0
  subiquity_client:
    git:
      url: https://github.com/canonical/ubuntu-desktop-installer.git
      path: packages/subiquity_client
  ubuntu_localizations: ^0.1.0
  ubuntu_session: ^0.0.4
  ubuntu_widgets:
    git:
      url: https://github.com/canonical/ubuntu-flutter-plugins.git
      path: packages/ubuntu_widgets
      ref: aba58a93465a4ed9040f805d513d47c49f1c941a
  ubuntu_wizard:
    git:
      url: https://github.com/canonical/ubuntu-desktop-installer.git
      path: packages/ubuntu_wizard
  yaru_widgets: ^2.4.0
