name: subiquity_client
description: Subiquity Client
version: 0.0.1
homepage: https://github.com/canonical/ubuntu-desktop-installer

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  diacritic:
  tuple:
  http: ^0.12.2

dev_dependencies:
  effective_dart: ^1.3.0
  flutter_test:
    sdk: flutter
