name: ubuntu_wsl_setup
description: Ubuntu WSL OOBE Setup Wizard
publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.10.0'

dependencies:
  args: ^2.2.0
  collection: ^1.17.0
  crypt: ^4.3.0
  diacritic: ^0.1.3
  flutter:
    sdk: flutter
  flutter_html: 3.0.0-beta.1
  flutter_svg: ^2.0.0
  form_field_validator: ^1.1.0
  path: ^1.8.0
  provider: ^6.0.0
  safe_change_notifier: ^0.3.0
  scroll_to_index: ^3.0.0
  subiquity_client:
    git:
      url: https://github.com/canonical/ubuntu-desktop-installer.git
      path: packages/subiquity_client
  ubuntu_localizations: ^0.3.3
  ubuntu_logger: ^0.0.3
  ubuntu_service: ^0.2.0
  ubuntu_utils:
    git:
      url: https://github.com/canonical/ubuntu-desktop-installer.git
      path: packages/ubuntu_utils
  ubuntu_widgets: ^0.1.0
  ubuntu_wizard:
    git:
      url: https://github.com/canonical/ubuntu-desktop-installer.git
      path: packages/ubuntu_wizard
  yaru: ^0.9.0
  yaru_icons: ^1.0.0
  yaru_widgets: ^2.5.0
  yaru_window: ^0.1.3

dev_dependencies:
  build_runner: ^2.2.0
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  mockito: 5.4.2
  subiquity_test:
    git:
      url: https://github.com/canonical/subiquity_client.dart.git
      path: packages/subiquity_test
  ubuntu_test: ^0.1.0-0
  yaru_test: ^0.1.0

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/
