name: ubuntu_wsl_setup
description: Ubuntu WSL OOBE Setup Wizard
publish_to: 'none'

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_html: ^2.1.1
  get_it: ^7.2.0
  provider: ^6.0.0
  scroll_to_index: ^2.0.0
  ubuntu_localizations:
    git:
      url: https://github.com/canonical/ubuntu-flutter-plugins.git
      path: packages/ubuntu_localizations
  ubuntu_logger:
    git:
      url: https://github.com/canonical/ubuntu-flutter-plugins.git
      path: packages/ubuntu_logger
  ubuntu_wizard:
    path: ../ubuntu_wizard
  url_launcher: ^6.0.9
  yaru: ^0.2.0

dev_dependencies:
  build_runner: ^2.1.1
  diacritic: ^0.1.3
  effective_dart: ^1.3.2
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  mockito: 5.0.14
  path: ^1.8.0
  ubuntu_test:
    path: ../ubuntu_test

flutter:
  uses-material-design: true
