name: ubuntu_wsl_setup
description: Ubuntu WSL OOBE Setup Wizard
publish_to: 'none'

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_html: ^3.0.0-0
  provider: ^6.0.0
  safe_change_notifier: ^0.1.0
  scroll_to_index: ^3.0.0
  ubuntu_localizations:
    git:
      url: https://github.com/canonical/ubuntu-flutter-plugins.git
      path: packages/ubuntu_localizations
  ubuntu_logger:
    git:
      url: https://github.com/canonical/ubuntu-flutter-plugins.git
      path: packages/ubuntu_logger
  ubuntu_service: ^0.1.0
  ubuntu_widgets:
    git:
      url: https://github.com/canonical/ubuntu-flutter-plugins.git
      path: packages/ubuntu_widgets
  ubuntu_wizard:
    path: ../ubuntu_wizard
  yaru: ^0.3.2

dev_dependencies:
  build_runner: ^2.1.1
  diacritic: ^0.1.3
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  mockito: 5.1.0
  path: ^1.8.0
  ubuntu_test:
    path: ../ubuntu_test

flutter:
  uses-material-design: true
