name: ubuntu_wsl_setup
description: Ubuntu WSL OOBE Setup Wizard
publish_to: 'none'

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=3.0.0"

dependencies:
  args: ^2.2.0
  diacritic: ^0.1.3
  flutter:
    sdk: flutter
  flutter_html: 3.0.0-alpha.5
  flutter_svg: ^1.1.0
  form_field_validator: ^1.1.0
  path: ^1.8.0
  provider: ^6.0.0
  safe_change_notifier: ^0.2.0
  scroll_to_index: ^3.0.0
  subiquity_client:
    path: ../subiquity_client
  ubuntu_localizations: ^0.0.3
  ubuntu_logger: ^0.0.1
  ubuntu_service: ^0.2.0
  ubuntu_widgets:
    git:
      url: https://github.com/canonical/ubuntu-flutter-plugins.git
      path: packages/ubuntu_widgets
  ubuntu_wizard:
    path: ../ubuntu_wizard
  yaru: ^0.5.0
  yaru_icons: ^1.0.0
  yaru_widgets: ^2.0.0-0

dev_dependencies:
  build_runner: ^2.2.0
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  mockito: 5.3.2
  ubuntu_test:
    path: ../ubuntu_test

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/
