name: Installer

on:
  push:
    branches:
      - main
      - 'ubuntu/**'
      - 'canary-*'
  pull_request:
  workflow_dispatch:

jobs:
  integration:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        target:
          - installation_slides_test.dart
          - screenshot_test.dart
          - ubuntu_desktop_installer_test.dart
      fail-fast: false

    steps:
      - name: Git checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install dependencies
        working-directory: packages/subiquity_client/subiquity
        run: |
          sudo apt update
          sudo apt install -y clang cmake curl libgtk-3-dev ninja-build pkg-config unzip xvfb
          sudo apt install -y dbus-x11 network-manager upower
          make install_deps

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          flutter-version: '3.10.x'

      - name: Flutter Doctor
        run: flutter doctor -v

      - name: Prepare environment
        run: |
          sudo loginctl enable-linger $USER
          sudo systemctl start user@$UID.service
          echo "XDG_RUNTIME_DIR=/run/user/$UID" >> $GITHUB_ENV
          # write any setting to force-start dconf.service (via xvfb because dbus-launch needs a display)
          xvfb-run -a gsettings set org.gnome.desktop.interface color-scheme "'default'"

      - name: Run tests
        run: |
          xvfb-run -a -s '-screen 0 1024x768x24 +extension GLX' \
            flutter test integration_test/${{matrix.target}}
        working-directory: packages/ubuntu_desktop_installer
        env:
          SUBIQUITY_REPLAY_TIMESCALE: 100
